/**
 * wikiSync.js
 *
 * Generates human-readable Markdown wiki pages for collections and upserts
 * them via the ADO Wiki REST API (through adoClient).
 *
 * Wiki page structure:
 *   ADO-SuperUI/
 *     Collections/
 *       {collection.name}    ← one page per collection
 *
 * Only the most recent comment per resource is shown in the wiki table to
 * avoid overflowing the markdown. All comments live in full in the YAML.
 */

// ── Markdown helpers ──────────────────────────────────────────────────────────

function escMd(str) {
  // Escape pipe characters inside table cells
  return String(str ?? "").replace(/\|/g, "\\|");
}

function fmtDate(iso) {
  if (!iso) return "";
  try { return new Date(iso).toISOString().slice(0, 10); } catch { return ""; }
}

function latestComment(comments) {
  if (!Array.isArray(comments) || !comments.length) return "";
  const c = comments[comments.length - 1];
  const text = escMd(c.text || "");
  const by   = escMd(c.author || "");
  const date = fmtDate(c.createdAt);
  return `${text} _(${by}, ${date})_`;
}

// ── Markdown generators ───────────────────────────────────────────────────────

function collectionNotes(comments, org) {
  if (!Array.isArray(comments) || !comments.length) return "";
  const rows = comments.map(c => {
    const text = escMd(c.text || "");
    const by   = escMd(c.author || "");
    const date = fmtDate(c.createdAt);
    return `> **${by}** (${date}): ${text}`;
  });
  return `## Collection Notes\n\n${rows.join("\n\n")}\n`;
}

function workItemsTable(workItemIds, org) {
  if (!workItemIds?.length) return "";
  const rows = workItemIds.map(id => {
    const url = org ? `[#${id}](https://dev.azure.com/${encodeURIComponent(org)}/_workitems/edit/${id})` : `#${id}`;
    return `| ${url} | | | |`;
  });
  return [
    "## Work Items",
    "",
    "| ID | Title | State | Assignee |",
    "|----|-------|-------|----------|",
    ...rows,
    "",
  ].join("\n");
}

function reposTable(repos, org) {
  if (!repos?.length) return "";
  const rows = repos.map(r => {
    const nameCell = escMd(r.name || r.id);
    const projectCell = escMd(r.project || "");
    const urlCell = r.remoteUrl ? `[link](${r.remoteUrl})` : "";
    const note = latestComment(r.comments);
    return `| ${nameCell} | ${projectCell} | ${urlCell} | ${note} |`;
  });
  return [
    "## Repositories",
    "",
    "| Name | Project | URL | Notes |",
    "|------|---------|-----|-------|",
    ...rows,
    "",
  ].join("\n");
}

function pipelinesTable(pipelines, org) {
  if (!pipelines?.length) return "";
  const rows = pipelines.map(p => {
    const nameCell    = escMd(p.name || p.id);
    const projectCell = escMd(p.project || "");
    const urlCell     = (org && p.project && p.id)
      ? `[link](https://dev.azure.com/${encodeURIComponent(org)}/${encodeURIComponent(p.project)}/_build?definitionId=${p.id})`
      : "";
    const note = latestComment(p.comments);
    return `| ${nameCell} | ${projectCell} | ${urlCell} | ${note} |`;
  });
  return [
    "## Pipelines",
    "",
    "| Name | Project | Build | Notes |",
    "|------|---------|-------|-------|",
    ...rows,
    "",
  ].join("\n");
}

function prsTable(prIds, org) {
  if (!prIds?.length) return "";
  const rows = prIds.map(id => `| ${escMd(id)} | | | |`);
  return [
    "## Pull Requests",
    "",
    "| ID | Title | Author | Status |",
    "|----|-------|--------|--------|",
    ...rows,
    "",
  ].join("\n");
}

// ── Main export ───────────────────────────────────────────────────────────────

/**
 * Generate the full Markdown content for a collection's wiki page.
 *
 * @param {object} collection  Migrated collection object
 * @param {string} org         ADO org name (for URL construction)
 * @returns {string} Markdown string
 */
export function generateWikiPage(collection, org) {
  const scopeLabel  = collection.scope === "personal" ? "Personal" : "Shared";

  const sections = [
    `# ${collection.icon || ""} ${collection.name}`.trim(),
    "",
    `> _Auto-generated by ADO SuperUI. Edit collections via the app, not directly._`,
    "",
    `**Scope:** ${scopeLabel}  `,
    "",
    collectionNotes(collection.comments, org),
    workItemsTable(collection.workItemIds, org),
    reposTable(collection.repos, org),
    pipelinesTable(collection.pipelines, org),
    prsTable(collection.prIds, org),
  ].filter(s => s !== undefined);

  return sections.join("\n");
}

/**
 * Upsert a wiki page for the given collection.
 * Silently swallows errors so wiki failures never block a collection save.
 *
 * @param {import('./adoClient').ADOClient} client
 * @param {{ project: string, wikiId: string }} wikiConfig
 * @param {object} collection
 * @param {string} org
 */
export async function syncCollectionToWiki(client, wikiConfig, collection, org) {
  if (!wikiConfig?.wikiId || !wikiConfig?.project) return;
  try {
    const content  = generateWikiPage(collection, org);
    const pagePath = `ADO-SuperUI/Collections/${collection.name}`;
    await client.upsertWikiPage(wikiConfig.project, wikiConfig.wikiId, pagePath, content);
  } catch (e) {
    console.warn("[wikiSync] Wiki page sync failed (non-fatal):", e.message);
  }
}
