import { describe, it, expect } from 'vitest';
import {
  generateWikiPage,
} from '../../src/lib/wikiSync.js';
import { sampleCollection, sampleWorkItems, sampleRepos, samplePipelines } from '../fixtures/adoResponses.js';

describe('wikiSync', () => {
  describe('generateWikiPage', () => {
    const org = 'myorg';

    it('should generate basic page with title and scope', () => {
      const collection = { id: '1', name: 'Test', scope: 'shared', icon: '🚀' };
      const result = generateWikiPage(collection, org);

      expect(result).toContain('# 🚀 Test');
      expect(result).toContain('**Scope:** Shared');
      expect(result).toContain('Auto-generated by ADO SuperUI');
    });

    it('should show Personal scope correctly', () => {
      const collection = { id: '1', name: 'My Dev', scope: 'personal', icon: '🔧' };
      const result = generateWikiPage(collection, org);

      expect(result).toContain('**Scope:** Personal');
    });

    it('should include work items section', () => {
      const collection = {
        ...sampleCollection,
        workItemIds: ['1001', '1002'],
      };

      const result = generateWikiPage(collection, org);

      expect(result).toContain('## Work Items');
      expect(result).toContain('| ID |');
      expect(result).toContain('#1001');
    });

    it('should include repositories section', () => {
      const collection = {
        ...sampleCollection,
        repos: [
          { id: 'repo-001', name: 'frontend-app', project: 'MyProject', remoteUrl: 'https://dev.azure.com/myorg/MyProject/_git/frontend-app' },
        ],
      };

      const result = generateWikiPage(collection, org);

      expect(result).toContain('## Repositories');
      expect(result).toContain('frontend-app');
    });

    it('should include pipeline section', () => {
      const collection = {
        ...sampleCollection,
        pipelines: [
          { id: '100', name: 'frontend-deploy', project: 'MyProject' },
        ],
      };

      const result = generateWikiPage(collection, org);

      expect(result).toContain('## Pipelines');
      expect(result).toContain('frontend-deploy');
    });

    it('should include PR section', () => {
      const collection = {
        ...sampleCollection,
        prIds: ['45'],
      };

      const result = generateWikiPage(collection, org);

      expect(result).toContain('## Pull Requests');
      expect(result).toContain('| ID |');
    });

    it('should include wiki pages section', () => {
      const collection = {
        ...sampleCollection,
        wikiPages: [
          { id: 'wiki-001', name: 'Getting Started', path: '/Getting Started', wikiName: 'docs', project: 'MyProject' },
        ],
      };

      const result = generateWikiPage(collection, org);

      expect(result).toContain('## Wiki Pages');
      expect(result).toContain('Getting Started');
    });

    it('should include collection notes/comments', () => {
      const collection = {
        ...sampleCollection,
        comments: [
          { text: 'Important note', author: 'Alice', createdAt: '2026-03-28T10:00:00Z' },
        ],
      };

      const result = generateWikiPage(collection, org);

      expect(result).toContain('## Collection Notes');
      expect(result).toContain('Important note');
      expect(result).toContain('Alice');
    });

    it('should include latest comment notes in resource tables', () => {
      const collection = {
        ...sampleCollection,
        repos: [
          { id: 'repo-001', comments: [{ text: 'Fixed auth issue', author: 'Bob', createdAt: '2026-03-29T10:00:00Z' }] },
        ],
        pipelines: [
          { id: '100', name: 'deploy', comments: [{ text: 'Needs approval', author: 'Carol', createdAt: '2026-03-29T11:00:00Z' }] },
        ],
      };

      const result = generateWikiPage(collection, org);

      expect(result).toContain('Fixed auth issue');
      expect(result).toContain('Needs approval');
    });

    it('should escape pipe characters in content', () => {
      const collection = {
        id: '1',
        name: 'Test | Pipe',
        scope: 'shared',
        icon: '📦',
        repos: [{ id: 'r1', name: 'repo with | in name' }],
      };

      const result = generateWikiPage(collection, org);

      expect(result).toContain('\\|');
    });

    it('should handle empty collection', () => {
      const collection = { id: 'empty', name: 'Empty', scope: 'shared' };
      const result = generateWikiPage(collection, org);

      expect(result).toContain('Empty');
      expect(result).not.toContain('undefined');
    });

    it('should handle null org gracefully', () => {
      const collection = { id: '1', name: 'Test', workItemIds: ['1001'] };
      const result = generateWikiPage(collection, null);

      expect(result).toContain('Test');
      expect(result).toContain('| #1001 |'); // No link when org is null
    });
  });
});